### ISSUE TITLE
Return after single play point locks player movement

### ISSUE THREAD

**Issue by SlimeDog** [MartenM/ServerTutorialPlus#27]
Spigot 1.15.2
ServerTutorialPlus 1.21.3

## The problem
The tour works correctly if I play the entire tour to end. But I cannot move after playing a single point.

## Steps to Reproduce

- [in creative mode]
- **/st playpoint biome-tour 1**
- [arrive at playpoint]
- **/essentials:back**
- [return to previous point]

The point (1 above) can be any of the 19 points on the tour. I cannot move laterally (in X- or Z-axis). I can fly (in Y-axis), in the same column (note: in creative mode).

Additional attempts:
- If I transport to a different world and return (Multiverse), I still cannot move
- If I disconnect/reconnect, I still cannot move.
- If I **/st play biome-tour**, I am transported to point 1, but sign-click does not transport me to point 2.
- If I **/st play biome-tour** and **/st quit**, then I can move again.

config.yml
```
no permission command: You do not have permission to execute this command.
no permission tutorial: You do not have enough permissions to play this tutorial.
enable first join tutorial: false
first join tutorial id: ''
language: English
npc:
  remove-invalid: false
  retry-time: 5
command-whitelist:
- help
```

tutorialsaves.yml
```
tutorials:
  biome-tour:
    stats:
      plays: 23
    invisible: false
    permission: false
    block-chat: false
    blocks-commands: true
    rewards: []
    command-whitelist: []
    points:
      '0':
        type: CLICK_BLOCK
        location: world -199.5 64.0 4535.5 90.0 0.0
        time: 2.0
        locplayer: true
        locview: false
        messages: []
        commands: []
        title:
          title: BAMBOO JUNGLE
          subtitle: biome tour
          fade-in: 20
          stay: 100
          fade-out: 20
        blocklocation: world -202.0 65.0 4535.0 0.0 0.0
        particles: false
        colour: 223 223 223
        teleport: true
      '1':
        type: CLICK_BLOCK
        location: world 185.5 63.0 -3523.5 90.0 0.0
        time: 2.0
        locplayer: true
        locview: false
        messages: []
        commands:
        - summon minecraft:cod 179.0 62.0 -3524.0
        title:
          title: BIRCH FOREST
          subtitle: biome tour
          fade-in: 20
          stay: 100
          fade-out: 20
        blocklocation: world 183.0 64.0 -3524.0 0.0 0.0
        particles: false
        colour: 223 223 223
        teleport: true
...
      '20':
        type: TIMED
        location: world 6.5 64.0 0.5 -108.8 0.0
        time: 1.0
        locplayer: false
        locview: true
        messages: []
        commands: []
        title:
          title: THE END
          subtitle: biome tour
          fade-in: 10
          stay: 0
          fade-out: 10
```
