### ISSUE TITLE
Colorcodes do not work in latest 1.18.2

### ISSUE THREAD

**Issue by CloudeLecaw** [MartenM/ServerTutorialPlus#67]
create a tutway with a title and subtitle
you will see the colorcods are written out instead of used

```
        title:
          title: '&2$$$&6Die Bank&2$$$'
          subtitle: '&4Folge den Partikeln'
```
![Snag_11441dc](https://user-images.githubusercontent.com/12080017/163273377-33879e9d-cbaa-4425-b4d0-90c0ee71e0c3.png)

```
[23:27:47 INFO]: This server is running Paper version git-Paper-286 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: d4a712d)
You are running the latest version
Previous version: git-Paper-285 (MC: 1.18.2)
```

Plugin Version: 1.23.4

**Comment by CloudeLecaw** [comment]
EDIT: 
Today i tested a bit with it arround and noticed that the colors work aggain if i replace all &-Codes with §-Codes
so it looks like the translation from the plugin from &-Colorcodes to §-Colorcodes broke :3

**Comment by MartenM** [comment]
Unable to replicate using the following configuration.
```yaml
tutorials:
  welcome:
    stats:
      plays: 16
    invisible: false
    permission: true
    block-chat: false
    blocks-commands: false
    rewards: []
    command-whitelist: []
    points:
      '0':
        type: TIMED
        location: world -93.9010023234268 101.49315828580635 15.187647099923886 -130.6497
          16.050196
        time: 6.0
        locplayer: true
        locview: false
        messages: []
        actionbar: '&7&lTutorial in progres...'
        commands: []
        setFly: true
        title:
          title: '&aWelcome'
          subtitle: '&bTo the fishing town server!'
          fade-in: 20
          stay: 40
          fade-out: 20
        sound:
          sound: BLOCK_BAMBOO_HIT
          pitch: 1.0
          volume: 1.0
```
![Example](https://i.imgur.com/F5xKRKX.png)
```
[12:59:32 INFO]: This server is running Paper version git-Paper-311 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: d70ac03)
You are running the latest version
```
